name: Auto-merge Dependabot PR

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    # if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1.5.1
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate cli
        run: echo "${{ steps.generate_token.outputs.token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs
        if: steps.dependabot_metadata.outputs.dependency-type == 'direct:development' && (steps.dependabot_metadata.outputs.update-type == 'version-update:semver-minor' || steps.dependabot_metadata.outputs.update-type == 'version-update:semver-patch')
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}