name: Auto-merge Dependabot PR

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: read

jobs:
  dependabot-pr:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    # if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@7bfa3a4717ef143a604ee0a99d859b8886a96d00 # v1.9.3
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}

      - name: Dependabot metadata
        id: dependabot_metadata
        uses: dependabot/fetch-metadata@5e5f99653a5b510e8555840e80cbf1514ad4af38 # v2.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate cli
        run: echo "${{ steps.generate_token.outputs.token }}" | gh auth login --with-token

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
